import crypto from 'crypto';
import os from 'os';
import path from 'path';
import { promises as fs } from 'fs';
import bcrypt from 'bcryptjs';
import { config } from '../config/config';
import { query,closePool } from '../config/database';

if(!config.db.database.startsWith('GYMFIT_DB_AUTH_RBAC_ACCEPTANCE_'))throw new Error('Refusing mutation outside isolated acceptance DB');
const base=process.env.ACCEPTANCE_BASE_URL||'http://127.0.0.1:5501/api';
const stamp=Date.now(); const password=()=>`Aa1!${crypto.randomBytes(18).toString('base64url')}`;
type Role='member'|'coach'|'admin'; type Account={id:number;email:string;password:string;role:Role;accessToken?:string;refreshToken?:string};
const accounts:Record<string,Account>={}; let assertions=0;let lastStatus=0;
function check(value:boolean,message:string){assertions++;if(!value)throw new Error(`${message} (last status ${lastStatus})`);}
async function call(method:string,url:string,token?:string,body?:unknown){const response=await fetch(base+url,{method,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});lastStatus=response.status;let data:unknown=null;try{data=await response.json();}catch{}return {status:response.status,data:data as {data?:Record<string,unknown>;message?:string}};}
async function seed(key:string,role:Role,active=true){const email=`accept-${key}-${stamp}@example.test`;const secret=password();const hash=await bcrypt.hash(secret,12);const result=await query<{id:number}>(`INSERT Users(email,password,name,role,is_active,email_verified,token_version) OUTPUT INSERTED.id VALUES(@email,@hash,@name,@role,@active,1,0)`,{email,hash,name:`Acceptance ${key}`,role,active});accounts[key]={id:result.recordset[0].id,email,password:secret,role};}
async function login(key:string){const a=accounts[key];const result=await call('POST','/auth/login',undefined,{email:a.email,password:a.password});check(result.status===200,`${key} login`);a.accessToken=String(result.data.data?.accessToken);a.refreshToken=String(result.data.data?.refreshToken);}
async function expect(method:string,url:string,key:string|undefined,status:number,body?:unknown){const result=await call(method,url,key?accounts[key].accessToken:undefined,body);check(result.status===status,`${method} ${url} ${key||'guest'} expected ${status} got ${result.status}`);return result;}

async function main(){
  for(const [key,role,active] of [['admin','admin',true],['coachA','coach',true],['coachB','coach',true],['memberA','member',true],['memberB','member',true],['inactive','member',false],['roleChanged','admin',true]] as Array<[string,Role,boolean]>)await seed(key,role,active);
  await query(`INSERT CRMCustomers(user_id,assigned_coach_id) VALUES(@ma,@ca),(@mb,@cb)`,{ma:accounts.memberA.id,ca:accounts.coachA.id,mb:accounts.memberB.id,cb:accounts.coachB.id});
  const crm=await query<{id:number;user_id:number}>('SELECT id,user_id FROM CRMCustomers WHERE user_id IN(@ma,@mb)',{ma:accounts.memberA.id,mb:accounts.memberB.id});const crmB=crm.recordset.find(row=>row.user_id===accounts.memberB.id)!.id;
  const booking=(await query<{id:number}>(`INSERT Bookings(coach_id,member_id,booking_date,start_time,end_time,status) OUTPUT INSERTED.id VALUES(@coach,@member,DATEADD(day,3,CAST(GETDATE() AS date)),'15:00','16:00','pending')`,{coach:accounts.coachB.id,member:accounts.memberB.id})).recordset[0].id;
  const ticket=(await query<{id:number}>(`INSERT Tickets(user_id,subject,category,priority,status,assigned_to) OUTPUT INSERTED.id VALUES(@member,'Acceptance ticket','general','medium','open',@coach)`,{member:accounts.memberB.id,coach:accounts.coachB.id})).recordset[0].id;
  const payment=(await query<{id:number}>(`INSERT Payments(user_id,amount,method,status) OUTPUT INSERTED.id VALUES(@member,100000,'manual','completed')`,{member:accounts.memberB.id})).recordset[0].id;
  const invoice=(await query<{id:number}>(`INSERT Invoices(invoice_number,user_id,payment_id,amount,tax,discount,total) OUTPUT INSERTED.id VALUES(@number,@member,@payment,100000,8000,0,108000)`,{number:`ACC-${stamp}`,member:accounts.memberB.id,payment})).recordset[0].id;
  const workout=(await query<{id:number}>(`INSERT Workouts(name,coach_id,difficulty,is_active) OUTPUT INSERTED.id VALUES('Acceptance workout',@coach,'beginner',1)`,{coach:accounts.coachB.id})).recordset[0].id;

  const registration={email:`accept-register-${stamp}@example.test`,password:password(),name:'Acceptance Registered',phone:'+84901234567'};let r=await call('POST','/auth/register',undefined,registration);check(r.status===201,'real registration');const registeredId=Number((r.data.data?.user as {id:number}).id);const registered=await query<{role:string;password:string}>('SELECT role,password FROM Users WHERE id=@id',{id:registeredId});check(registered.recordset[0].role==='member'&&registered.recordset[0].password!==registration.password,'registration role/hash');check((await call('POST','/auth/login',undefined,{email:registration.email,password:registration.password})).status===200,'registered login');check((await call('POST','/auth/register',undefined,registration)).status===409,'duplicate registration');check((await call('POST','/auth/register',undefined,{...registration,email:`bad-${stamp}@example.test`,role:'admin'})).status===400,'role mass assignment');check((await call('POST','/auth/register',undefined,{email:'invalid',password:'x'})).status===400,'invalid registration');
  for(const key of ['admin','coachA','coachB','memberA','memberB','roleChanged'])await login(key);r=await call('POST','/auth/login',undefined,{email:accounts.inactive.email,password:accounts.inactive.password});check(r.status===401,'inactive login');const wrongA=await call('POST','/auth/login',undefined,{email:accounts.memberA.email,password:'incorrect'});const wrongB=await call('POST','/auth/login',undefined,{email:`missing-${stamp}@example.test`,password:'incorrect'});check(wrongA.status===wrongB.status&&wrongA.data.message===wrongB.data.message,'generic login error');

  const oldRefresh=accounts.memberA.refreshToken!;r=await call('POST','/auth/refresh',undefined,{refreshToken:oldRefresh});check(r.status===200,'refresh rotation');const rotated=String(r.data.data?.refreshToken);check((await call('POST','/auth/refresh',undefined,{refreshToken:oldRefresh})).status===401,'refresh replay');check((await call('POST','/auth/refresh',undefined,{refreshToken:rotated})).status===401,'family revoked after replay');await login('memberA');const logoutRefresh=accounts.memberA.refreshToken!;const beforeLogout=await call('GET','/auth/me',accounts.memberA.accessToken);check(beforeLogout.status===200,`pre-logout access ${beforeLogout.status}`);const logoutResult=await call('POST','/auth/logout',accounts.memberA.accessToken);check(logoutResult.status===200,`logout status ${logoutResult.status}`);check((await call('POST','/auth/refresh',undefined,{refreshToken:logoutRefresh})).status===401,'logout revocation');await login('memberA');

  const matrix:Array<[string,string,number,number,number]>=[['/auth/me','GET',200,200,200],['/users','GET',200,200,200],['/crm','GET',403,200,200],['/tickets','GET',200,200,200],['/invoices','GET',200,403,200],['/bookings','GET',200,200,200],['/referral/my-code','GET',200,200,200],['/loyalty/points','GET',200,403,403],['/plans/my-membership','GET',200,403,403],['/videos','GET',403,200,200],['/coupons','GET',403,403,200],['/audit','GET',403,403,200],['/analytics/dashboard','GET',403,403,200],['/revenue/dashboard','GET',403,403,200],['/backup','GET',403,403,200],['/admin/products','GET',403,403,200],['/admin/categories','GET',403,403,200],['/admin/inventory','GET',403,403,200],['/admin/orders','GET',403,403,200],['/orders','GET',200,403,403]];
  for(const [url,method,member,coach,admin] of matrix){await expect(method,url,undefined,401);await expect(method,url,'memberA',member);await expect(method,url,'memberB',member);await expect(method,url,'coachA',coach);await expect(method,url,'coachB',coach);await expect(method,url,'admin',admin);}
  await expect('GET',`/tickets/${ticket}`,'memberA',404);await expect('GET',`/tickets/${ticket}`,'memberB',200);await expect('GET',`/invoices/${invoice}`,'memberA',404);await expect('GET',`/invoices/${invoice}`,'memberB',200);await expect('GET',`/crm/${crmB}`,'coachA',404);await expect('GET',`/crm/${crmB}`,'coachB',200);await expect('PUT',`/bookings/${booking}/status`,'coachA',404,{status:'confirmed'});await expect('PUT',`/bookings/${booking}/status`,'coachB',200,{status:'confirmed'});await expect('PUT',`/videos/${workout}`,'coachA',404,{name:'Blocked',coach_id:accounts.coachA.id});await expect('POST','/media/process/1',undefined,401);await expect('POST','/media/process/1','memberA',403);await expect('POST','/media/process/1','coachA',403);

  const bookingBody={coach_id:accounts.coachA.id,booking_date:new Date(Date.now()+(5+(stamp%100))*86400000).toISOString().slice(0,10),start_time:'14:00',end_time:'15:00'};const concurrent=await Promise.all([call('POST','/bookings',accounts.memberA.accessToken,bookingBody),call('POST','/bookings',accounts.memberB.accessToken,bookingBody)]);check(concurrent.map(x=>x.status).sort().join(',')==='201,409','booking concurrency');const daily=await Promise.all([call('POST','/loyalty/daily-login',accounts.memberA.accessToken),call('POST','/loyalty/daily-login',accounts.memberA.accessToken)]);check(daily.every(x=>x.status===200),'daily concurrency responses');check(Number((await query('SELECT COUNT(*) count FROM PointTransactions WHERE user_id=@id AND source=\'login\' AND CAST(created_at AS date)=CAST(GETDATE() AS date)',{id:accounts.memberA.id})).recordset[0].count)===1,'daily idempotency');

  const privileged=accounts.roleChanged.accessToken!,roleRefresh=accounts.roleChanged.refreshToken!;await expect('PATCH',`/users/${accounts.roleChanged.id}/security`,'admin',200,{role:'member'});check((await call('GET','/admin/products',privileged)).status===401,'old role token invalidated');check((await call('POST','/auth/refresh',undefined,{refreshToken:roleRefresh})).status===401,'old role refresh invalidated');const disabledAccess=accounts.memberB.accessToken!,disabledRefresh=accounts.memberB.refreshToken!;await expect('PATCH',`/users/${accounts.memberB.id}/security`,'admin',200,{is_active:false});check((await call('GET','/auth/me',disabledAccess)).status===401,'inactive access invalidated');check((await call('POST','/auth/refresh',undefined,{refreshToken:disabledRefresh})).status===401,'inactive refresh invalidated');

  await fs.writeFile(path.join(os.tmpdir(),`gymfit-auth-browser-${config.db.database}.json`),JSON.stringify({base:base.replace('/api',''),admin:{email:accounts.admin.email,password:accounts.admin.password},coach:{email:accounts.coachA.email,password:accounts.coachA.password},member:{email:accounts.memberA.email,password:accounts.memberA.password}}),{mode:0o600});
  console.log(JSON.stringify({verdict:'AUTOMATED_AUTH_RBAC_ACCEPTANCE_PASS',assertions,matrix_routes:matrix.length,actors:6}));
}
main().finally(async()=>{await closePool();}).catch(error=>{console.error(error instanceof Error?error.message:'Acceptance failed');process.exitCode=1;});
