import { FormEvent,useCallback,useEffect,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { AxiosError } from 'axios';
import toast from 'react-hot-toast';
import { Copy,RefreshCw } from 'lucide-react';
import { ordersApi } from '../../services/ordersApi';
import type { CustomerOrderDetail,PaymentNotificationResult,PaymentStatus } from '../../types/orders';
const labels:Record<PaymentStatus,string>={UNPAID:'Chưa thanh toán',PENDING:'Chờ xác nhận',PAID:'Đã thanh toán',FAILED:'Chưa xác nhận được',PARTIALLY_REFUNDED:'Hoàn tiền một phần',REFUNDED:'Đã hoàn tiền'};
const errorMessage=(error:unknown)=>error instanceof AxiosError&&typeof error.response?.data?.message==='string'?error.response.data.message:'Unable to load order';
const money=(value:number,currency:string)=>`${value.toFixed(2)} ${currency}`;
const copy=async(value:string,label:string)=>{try{await navigator.clipboard.writeText(value);toast.success(`${label} copied`)}catch{toast.error('Unable to copy. Please copy it manually.')}};
export default function CustomerOrderDetailPage(){
 const id=Number(useParams().orderId),[order,setOrder]=useState<CustomerOrderDetail|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[reference,setReference]=useState(''),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{setOrder((await ordersApi.getCustomerOrder(id)).data.data)}catch(e){setError(errorMessage(e))}finally{setLoading(false)}},[id]);useEffect(()=>{void load()},[load]);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!order||saving)return;const value=reference.trim();if(value.length>255){setError('Payment reference must be 255 characters or fewer');return}setSaving(true);setError('');try{const result:PaymentNotificationResult=(await ordersApi.notifyOrderPayment(order.id,value?{paymentReference:value}:{})).data.data;await load();if(result.emailSent)toast.success('Đã gửi thông báo chuyển khoản. Vui lòng chờ Admin xác nhận.');else toast.error('Thông tin thanh toán đã được ghi nhận, nhưng email thông báo chưa gửi được.')}catch(e){setError(errorMessage(e))}finally{setSaving(false)}};
 if(loading)return <div className="p-8 text-center text-slate-400">Loading order…</div>;
 if(error&&!order)return <div className="space-y-4 p-8"><Link className="text-blue-400" to="/orders">Back to Orders</Link><div role="alert" className="rounded-xl border border-red-500/30 bg-red-500/10 p-5 text-red-300">{error}<button type="button" className="ml-3 underline" onClick={()=>void load()}>Retry</button></div></div>;
 if(!order)return null;
 const status=order.paymentStatus,bank=order.bankTransfer,showQr=status==='UNPAID'||status==='PENDING'||status==='FAILED';
 return <div className="space-y-5 p-4 md:p-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link className="text-blue-400" to="/orders">Back to Orders</Link><h1 className="mt-2 text-2xl font-bold">{order.orderNumber}</h1><p className="text-sm text-slate-400">Order ID: {order.id}</p></div><button type="button" className="btn-secondary flex items-center gap-2" aria-label="Refresh order" disabled={loading} onClick={()=>void load()}><RefreshCw size={16} aria-hidden="true"/>Refresh</button></div>
 <section className="rounded-xl border border-slate-800 bg-slate-950 p-5"><div className="grid gap-2 sm:grid-cols-2"><p>Order status: <strong>{order.orderStatus}</strong></p><p>Payment status: <strong>{labels[status]}</strong></p><p>Created: {new Date(order.createdAt).toLocaleString()}</p><p>Updated: {new Date(order.updatedAt).toLocaleString()}</p></div></section>
 <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-xl border border-slate-800 bg-slate-950 p-5"><h2 className="mb-3 text-lg font-semibold">Customer</h2><p>{order.customerName}</p><p>{order.customerEmail}</p><p>{order.customerPhone||'—'}</p></section><section className="rounded-xl border border-slate-800 bg-slate-950 p-5"><h2 className="mb-3 text-lg font-semibold">Shipping</h2><p>{order.addressLine1||'—'}</p><p>{order.addressLine2||'—'}</p><p>{[order.city,order.state,order.postalCode].filter(Boolean).join(', ')||'—'}</p><p>{order.country||'—'}</p></section></div>
 <section className="overflow-x-auto rounded-xl border border-slate-800"><h2 className="p-5 text-lg font-semibold">Items</h2><table className="w-full min-w-[800px] text-sm"><thead><tr><th>Product</th><th>Variant</th><th>SKU</th><th>Quantity</th><th>Unit price</th><th>Line total</th></tr></thead><tbody>{order.items.map(item=><tr key={item.id} className="border-t border-slate-800"><td className="p-3">{item.productName}</td><td>{item.variantName}</td><td>{item.sku}</td><td>{item.quantity}</td><td>{money(item.unitPrice,order.currency)}</td><td>{money(item.lineTotal,order.currency)}</td></tr>)}</tbody></table></section>
 <section className="rounded-xl border border-slate-800 bg-slate-950 p-5"><h2 className="mb-3 text-lg font-semibold">Pricing</h2><div className="grid max-w-md gap-2 sm:grid-cols-2"><span>Subtotal</span><span>{money(order.subtotal,order.currency)}</span><span>Discount</span><span>{money(order.discountAmount,order.currency)}</span><span>Shipping</span><span>{money(order.shippingAmount,order.currency)}</span><span>Tax</span><span>{money(order.taxAmount,order.currency)}</span><strong>Total</strong><strong>{money(order.totalAmount,order.currency)}</strong><span>Currency</span><span>{order.currency}</span></div></section>
 {showQr&&<section className="grid gap-5 rounded-xl border border-blue-500/30 bg-slate-950 p-5 lg:grid-cols-[240px_1fr]"><div><h2 className="mb-3 text-lg font-semibold">Thanh toán chuyển khoản</h2><img className="h-auto w-full rounded-lg bg-white p-2" src={bank?.qrImageUrl||'/images/payment/bank-qr.jpg'} alt="Mã QR thanh toán chuyển khoản GymFit"/></div><div className="space-y-3"><p>Bank name: {bank?.bankName||'—'}</p><p>Account name: {bank?.accountName||'—'}</p><div className="flex items-center gap-2"><span>Account number: {bank?.accountNumber||'—'}</span>{bank?.accountNumber&&<button type="button" title="Copy account number" aria-label="Copy account number" onClick={()=>void copy(bank.accountNumber||'','Account number')}><Copy size={16} aria-hidden="true"/></button>}</div><p>Amount: {money(order.totalAmount,order.currency)}</p><p>Transfer content: {bank?.transferContent||`GYMFIT ${order.orderNumber}`}</p>{bank?.transferContent&&<button type="button" className="btn-secondary" title="Copy transfer content" aria-label="Copy transfer content" onClick={()=>void copy(bank.transferContent,'Transfer content')}><Copy size={16} aria-hidden="true"/> Copy transfer content</button>}<ol className="list-decimal space-y-1 pl-5 text-sm text-slate-300"><li>Quét mã QR hoặc chuyển khoản vào tài khoản hiển thị.</li><li>Chuyển đúng số tiền của đơn hàng.</li><li>Ghi đúng nội dung chuyển khoản.</li><li>Sau khi chuyển khoản, bấm “Tôi đã chuyển khoản”.</li><li>Admin sẽ kiểm tra tài khoản và xác nhận thanh toán.</li></ol><p className="text-sm text-amber-300">Hệ thống không tự động kiểm tra giao dịch ngân hàng.</p>{status==='FAILED'&&<p className="text-amber-300">Chưa xác nhận được thanh toán. Vui lòng kiểm tra số tiền và nội dung chuyển khoản.</p>}{status==='PENDING'&&<p className="text-amber-300">Đang chờ Admin xác nhận thanh toán.</p>}{status==='UNPAID'&&<form className="space-y-3" onSubmit={submit}><label>Mã giao dịch hoặc ghi chú thanh toán — không bắt buộc<input aria-label="Payment reference" maxLength={255} className="input-field mt-1 w-full" value={reference} onChange={e=>setReference(e.target.value)}/></label>{error&&<p role="alert" className="text-sm text-red-400">{error}</p>}<button type="submit" className="btn-primary" disabled={saving}>{saving?'Sending…':'Tôi đã chuyển khoản'}</button></form>}</div></section>}
 </div>;
}
