import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import api from '../../api/axios';
import { useProductsStore } from '../../stores/productsStore';
import type { ProductDetailResponse } from '../../types/product';
import type { CheckoutFormErrors, CheckoutFormValues, CreateOrderItemInput } from '../../types/orders';
import { ordersApi } from '../../services/ordersApi';

const initial: CheckoutFormValues = { customerName:'', customerPhone:'', addressLine1:'', addressLine2:'', city:'', state:'', postalCode:'', country:'Vietnam' };
type Resolved = { variantId:number; quantity:number; name:string; variantName:string; sku:string; price:number };

export default function CheckoutPage() {
  const { cartItems, clearCart } = useProductsStore();
  const navigate = useNavigate();
  const [form, setForm] = useState(initial); const [errors, setErrors] = useState<CheckoutFormErrors>({});
  const [items, setItems] = useState<Resolved[]>([]); const [loadingItems, setLoadingItems] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('');
  useEffect(() => { let active = true; (async () => { try { const resolved = await Promise.all(cartItems.map(async item => { const r = await api.get<ProductDetailResponse>(`/products/${item.productId}`); const v = r.data.data.display_variant; return { variantId:v.id, quantity:item.quantity, name:r.data.data.product_name, variantName:v.variant_name, sku:v.sku, price:v.effective_price }; })); const map = new Map<number, Resolved>(); resolved.forEach(i => { const old=map.get(i.variantId); map.set(i.variantId, old ? {...i, quantity:old.quantity+i.quantity} : i); }); if (active) setItems([...map.values()]); } catch { if (active) setError('Unable to load current product availability.'); } finally { if (active) setLoadingItems(false); } })(); return () => { active=false; }; }, [cartItems]);
  const total = useMemo(() => items.reduce((s,i)=>s+i.price*i.quantity,0), [items]);
  const update = (key:keyof CheckoutFormValues, value:string) => setForm(f=>({...f,[key]:value}));
  const validate = () => { const e:CheckoutFormErrors={}; if(!form.customerName.trim())e.customerName='Name is required.'; if(!form.customerPhone.trim())e.customerPhone='Phone is required.'; if(!form.addressLine1.trim())e.addressLine1='Address is required.'; if(!form.city.trim())e.city='City is required.'; if(!form.country.trim())e.country='Country is required.'; if(!items.length)e.items='Your cart is empty.'; if(items.some(i=>!Number.isSafeInteger(i.quantity)||i.quantity<=0||!Number.isSafeInteger(i.variantId)||i.variantId<=0))e.items='Cart contains an invalid item.'; setErrors(e); return !Object.keys(e).length; };
  const submit = async (event:FormEvent) => { event.preventDefault(); if(submitting||!validate())return; setSubmitting(true); setError(''); const payload={customerName:form.customerName.trim(),customerPhone:form.customerPhone.trim(),shippingAddressLine1:form.addressLine1.trim(),shippingAddressLine2:form.addressLine2.trim()||undefined,shippingCity:form.city.trim(),shippingState:form.state.trim()||undefined,shippingPostalCode:form.postalCode.trim()||undefined,shippingCountry:form.country.trim(),items:items.map(({variantId,quantity}:CreateOrderItemInput)=>({variantId,quantity}))}; try { const r=await ordersApi.createOrder(payload); clearCart(); navigate(`/orders/${r.data.data.id}`); } catch (err) { const message=(err as {response?:{data?:{message?:string}}}).response?.data?.message || 'Unable to create order.'; setError(message); } finally { setSubmitting(false); } };
  if (!cartItems.length) return <main className="p-8 text-white"><h1 className="text-2xl font-bold">Checkout</h1><p className="mt-4 text-white/70">Your cart is empty.</p><Link className="mt-6 inline-block text-emerald-400" to="/products">Back to products</Link></main>;
  const fields:[keyof CheckoutFormValues,string][]=[['customerName','Name'],['customerPhone','Phone'],['addressLine1','Address'],['addressLine2','Address line 2'],['city','City'],['state','State'],['postalCode','Postal code'],['country','Country']];
  return <main className="mx-auto max-w-6xl p-6 text-white"><h1 className="mb-6 text-3xl font-bold">Checkout</h1>{error&&<p role="alert" className="mb-4 rounded bg-red-500/15 p-3 text-red-300">{error}</p>}<div className="grid gap-8 lg:grid-cols-2"><section><h2 className="mb-4 text-xl font-semibold">Shipping information</h2><form onSubmit={submit} className="space-y-4">{fields.map(([key,label])=><label key={key} className="block text-sm">{label}{!['addressLine2','state','postalCode'].includes(key)&&' *'}<input aria-invalid={!!errors[key]} value={form[key]} onChange={e=>update(key,e.target.value)} className="mt-1 w-full rounded border border-white/15 bg-white/5 p-3" />{errors[key]&&<span className="text-red-300">{errors[key]}</span>}</label>)}{errors.items&&<p className="text-red-300">{errors.items}</p>}<button type="submit" disabled={submitting||loadingItems} className="rounded bg-emerald-500 px-5 py-3 font-semibold text-black disabled:opacity-50">{submitting?'Creating order…':'Place order'}</button></form></section><section><h2 className="mb-4 text-xl font-semibold">Order summary</h2>{loadingItems?<p>Loading current prices…</p>:items.map(i=><div key={i.variantId} className="flex justify-between border-b border-white/10 py-3"><div><p>{i.name}</p><p className="text-sm text-white/60">{i.variantName} · {i.sku} × {i.quantity}</p></div><span>{(i.price*i.quantity).toLocaleString()} VND</span></div>)}<p className="mt-5 text-right text-xl font-bold">Total: {total.toLocaleString()} VND</p><p className="mt-3 text-sm text-white/60">Prices and stock are confirmed by the server when the order is submitted.</p></section></div></main>;
}
