import type { ReactNode } from 'react';
import { AlertCircle, ArrowUpRight, Inbox, RefreshCw } from 'lucide-react';
import { Link } from 'react-router-dom';

export interface MetricCardProps { title:string; value:string|number; detail?:string; icon?:ReactNode; tone?:'lime'|'blue'|'amber'|'slate'; loading?:boolean; }
export function DashboardPageHeader({title,description,eyebrow,action}:{title:string;description:string;eyebrow?:string;action?:ReactNode}) { return <header className="dashboard-header"><div><p className="dashboard-eyebrow">{eyebrow || 'GYMFIT COMMAND CENTER'}</p><h1>{title}</h1><p className="dashboard-description">{description}</p></div>{action && <div className="dashboard-header-action">{action}</div>}</header>; }
export function MetricCard({title,value,detail,icon,tone='lime',loading}:MetricCardProps) { return <article className={`metric-card metric-${tone}`} aria-busy={loading}><div className="metric-top"><span>{title}</span><span className="metric-icon">{icon}</span></div>{loading ? <div className="skeleton metric-skeleton" /> : <strong>{value}</strong>}{detail && <small>{detail}</small>}</article>; }
export function DashboardPanel({title,description,action,children,className=''}:{title:string;description?:string;action?:ReactNode;children:ReactNode;className?:string}) { return <section className={`dashboard-panel ${className}`}><div className="panel-header"><div><h2>{title}</h2>{description && <p>{description}</p>}</div>{action}</div>{children}</section>; }
export function PanelError({message,onRetry}:{message:string;onRetry?:()=>void}) { return <div className="panel-state panel-error"><AlertCircle size={18}/><div><strong>Không thể tải khu vực này</strong><p>{message}</p></div>{onRetry && <button className="icon-button" onClick={onRetry} aria-label="Thử lại"><RefreshCw size={16}/></button>}</div>; }
export function EmptyState({title,description,action}:{title:string;description:string;action?:ReactNode}) { return <div className="panel-state panel-empty"><Inbox size={20}/><div><strong>{title}</strong><p>{description}</p></div>{action}</div>; }
export function QuickAction({to,title,description,icon}:{to:string;title:string;description:string;icon:ReactNode}) { return <Link to={to} className="quick-action"><span className="quick-icon">{icon}</span><span><strong>{title}</strong><small>{description}</small></span><ArrowUpRight size={16}/></Link>; }
export function DashboardSkeleton() { return <div className="dashboard-skeleton" aria-label="Đang tải dashboard"><div className="skeleton skeleton-title"/><div className="skeleton-grid">{[1,2,3,4].map(item=><div className="skeleton skeleton-card" key={item}/>)}</div><div className="skeleton skeleton-panel"/></div>; }
export const formatVnd=(value:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(value);
