import { getPool, sql } from '../../config/database';
import { AppError } from '../../middleware/errorHandler';

type Query = Record<string, string | number | boolean | Date | undefined>;
type InventoryRow = { inventory_id:number; variant_id:number; on_hand:number; reserved:number; available:number; low_stock_threshold:number };
const fromClause = `FROM dbo.Inventory i JOIN dbo.ProductVariants v ON v.id=i.variant_id JOIN dbo.Products p ON p.id=v.product_id LEFT JOIN dbo.Brands b ON b.id=p.brand_id LEFT JOIN dbo.Categories c ON c.id=p.category_id`;
const fields = `i.id inventory_id,i.variant_id,i.on_hand,i.reserved,i.available,i.low_stock_threshold,i.last_restocked,i.updated_at,p.id product_id,p.product_name,p.slug product_slug,b.id brand_id,b.name brand,c.id category_id,c.name category,v.variant_name,v.sku,v.is_active,v.is_default,CASE WHEN i.available<=0 THEN 'OUT_OF_STOCK' WHEN i.available<=i.low_stock_threshold THEN 'LOW_STOCK' ELSE 'IN_STOCK' END stock_status`;
const detailSelect = `SELECT ${fields} ${fromClause}`;
const statusExpression = `CASE WHEN i.available<=0 THEN 'OUT_OF_STOCK' WHEN i.available<=i.low_stock_threshold THEN 'LOW_STOCK' ELSE 'IN_STOCK' END`;

async function detail(variantId:number) { const pool=await getPool(); const result=await pool.request().input('variantId',sql.Int,variantId).query(`${detailSelect} WHERE i.variant_id=@variantId; SELECT TOP 10 ia.*,u.id admin_id,u.name admin_name,u.email admin_email FROM dbo.InventoryAdjustments ia JOIN dbo.Users u ON u.id=ia.performed_by WHERE ia.variant_id=@variantId ORDER BY ia.created_at DESC,ia.id DESC`); if(!result.recordset[0]) throw new AppError(404,'Inventory not found'); return {...(result.recordset[0] as InventoryRow),latest_adjustments:(result.recordsets as unknown as { [key:number]: unknown[] })[1]||[]}; }

export const adminInventoryService={
  async list(query:Query) { const page=Number(query.page)||1,limit=Number(query.limit)||20,clauses:string[]=[]; const request=(await getPool()).request().input('offset',sql.Int,(page-1)*limit).input('limit',sql.Int,limit); if(query.search){request.input('search',sql.NVarChar(200),`%${String(query.search)}%`);clauses.push('(p.product_name LIKE @search OR v.sku LIKE @search)');} for(const [key,column] of [['categoryId','p.category_id'],['brandId','p.brand_id'],['productId','p.id']] as const)if(query[key]){request.input(key,sql.Int,Number(query[key]));clauses.push(`${column}=@${key}`);} if(query.status){request.input('status',sql.NVarChar(20),String(query.status));clauses.push(`${statusExpression}=@status`);} if(query.lowStock===true)clauses.push(`${statusExpression}='LOW_STOCK'`); const sort:{[key:string]:string}={product_name:'p.product_name',sku:'v.sku',on_hand:'i.on_hand',reserved:'i.reserved',available:'i.available',low_stock_threshold:'i.low_stock_threshold',updated_at:'i.updated_at'}; const order=sort[String(query.sortBy)]||'i.updated_at'; const direction=query.sortOrder==='asc'?'ASC':'DESC'; const where=clauses.length?`WHERE ${clauses.join(' AND ')}`:''; const result=await request.query(`SELECT ${fields},COUNT_BIG(*) OVER() total_count ${fromClause} ${where} ORDER BY ${order} ${direction},i.id ASC OFFSET @offset ROWS FETCH NEXT @limit ROWS ONLY`); return {data:result.recordset,page,limit,total:Number(result.recordset[0]?.total_count||0)}; },
  detail,
  async adjust(variantId:number,input:Record<string,unknown>,adminId:number){const pool=await getPool();const tx=pool.transaction();await tx.begin();try{const row=await tx.request().input('variantId',sql.Int,variantId).query('SELECT id,variant_id,on_hand,reserved FROM dbo.Inventory WITH (UPDLOCK,HOLDLOCK) WHERE variant_id=@variantId');if(!row.recordset[0])throw new AppError(404,'Inventory not found');const inv=row.recordset[0] as {id:number;on_hand:number;reserved:number};const target=input.targetOnHand,provided=input.quantityDelta;const delta=target===undefined?Number(provided):Number(target)-inv.on_hand;if(!Number.isSafeInteger(delta)||delta===0)throw new AppError(400,'Stock adjustment must change on_hand');if(input.type==='RESTOCK'&&delta<=0)throw new AppError(400,'RESTOCK requires a positive delta');const next=inv.on_hand+delta;if(next<0)throw new AppError(409,'Stock cannot become negative');if(next<inv.reserved)throw new AppError(409,'Stock cannot be below reserved quantity');await tx.request().input('id',sql.Int,inv.id).input('onHand',sql.Int,next).input('restock',sql.Bit,input.type==='RESTOCK').query('UPDATE dbo.Inventory SET on_hand=@onHand,last_restocked=CASE WHEN @restock=1 THEN SYSUTCDATETIME() ELSE last_restocked END,updated_at=SYSUTCDATETIME() WHERE id=@id');const adjustment=await tx.request().input('inventoryId',sql.Int,inv.id).input('variantId',sql.Int,variantId).input('type',sql.NVarChar(40),String(input.type)).input('delta',sql.Int,delta).input('previous',sql.Int,inv.on_hand).input('next',sql.Int,next).input('reason',sql.NVarChar(500),String(input.reason).trim()).input('referenceType',sql.NVarChar(100),input.referenceType??null).input('referenceId',sql.NVarChar(100),input.referenceId??null).input('adminId',sql.Int,adminId).query('INSERT dbo.InventoryAdjustments(inventory_id,variant_id,adjustment_type,quantity_delta,previous_on_hand,new_on_hand,reason,reference_type,reference_id,performed_by,created_at) OUTPUT INSERTED.id VALUES(@inventoryId,@variantId,@type,@delta,@previous,@next,@reason,@referenceType,@referenceId,@adminId,SYSUTCDATETIME())');const fresh=await tx.request().input('id',sql.Int,inv.id).query('SELECT available,reserved FROM dbo.Inventory WHERE id=@id');await tx.commit();return {adjustmentId:adjustment.recordset[0].id,variantId,previousOnHand:inv.on_hand,quantityDelta:delta,newOnHand:next,reserved:fresh.recordset[0].reserved,available:fresh.recordset[0].available,type:input.type};}catch(error:unknown){await tx.rollback();throw error;}},
  async threshold(variantId:number,value:number){const pool=await getPool();const tx=pool.transaction();await tx.begin();try{const row=await tx.request().input('variantId',sql.Int,variantId).query('SELECT id FROM dbo.Inventory WITH (UPDLOCK,HOLDLOCK) WHERE variant_id=@variantId');if(!row.recordset[0])throw new AppError(404,'Inventory not found');await tx.request().input('id',sql.Int,row.recordset[0].id).input('value',sql.Int,value).query('UPDATE dbo.Inventory SET low_stock_threshold=@value,updated_at=SYSUTCDATETIME() WHERE id=@id');await tx.commit();return detail(variantId);}catch(error:unknown){await tx.rollback();throw error;}},
  async history(variantId:number,query:Query){await detail(variantId);const page=Number(query.page)||1,limit=Number(query.limit)||20,clauses=['ia.variant_id=@variantId'];const request=(await getPool()).request().input('variantId',sql.Int,variantId).input('offset',sql.Int,(page-1)*limit).input('limit',sql.Int,limit);if(query.type){request.input('type',sql.NVarChar(40),String(query.type));clauses.push('ia.adjustment_type=@type');}if(query.dateFrom){request.input('dateFrom',sql.DateTime2,query.dateFrom as Date);clauses.push('ia.created_at>=@dateFrom');}if(query.dateTo){request.input('dateTo',sql.DateTime2,query.dateTo as Date);clauses.push('ia.created_at<=@dateTo');}const result=await request.query(`SELECT ia.*,u.id admin_id,u.name admin_name,u.email admin_email,COUNT_BIG(*) OVER() total_count FROM dbo.InventoryAdjustments ia JOIN dbo.Users u ON u.id=ia.performed_by WHERE ${clauses.join(' AND ')} ORDER BY ia.created_at DESC,ia.id DESC OFFSET @offset ROWS FETCH NEXT @limit ROWS ONLY`);return {data:result.recordset,page,limit,total:Number(result.recordset[0]?.total_count||0)};}
};
