import { ChangeEvent, FormEvent, useCallback, useEffect, useState } from 'react';
import { Edit3, ImagePlus, Plus, Search, Star, Trash2, X } from 'lucide-react';
import toast from 'react-hot-toast';
import api from '../../api/axios';
import ProductImage from '../../components/products/ProductImage';
import type { Product } from '../../types/product';

interface Choice { id:number; name:string; slug:string }
interface Filters { categories:Choice[]; brands:Choice[] }
interface FormState { product_name:string; description:string; sku:string; price:string; sale_price:string; stock:string; category_id:string; brand_id:string; is_active:boolean; is_featured:boolean; is_on_sale:boolean }
const emptyForm: FormState = { product_name:'',description:'',sku:'',price:'',sale_price:'',stock:'0',category_id:'',brand_id:'',is_active:true,is_featured:false,is_on_sale:false };

export default function AdminProductsPage() {
  const [products,setProducts]=useState<Product[]>([]); const [filters,setFilters]=useState<Filters>({categories:[],brands:[]});
  const [page,setPage]=useState(1); const [pages,setPages]=useState(1); const [total,setTotal]=useState(0); const [search,setSearch]=useState(''); const [category,setCategory]=useState(''); const [status,setStatus]=useState(''); const [sort,setSort]=useState('updated_desc');
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [editing,setEditing]=useState<Product|null>(null); const [form,setForm]=useState<FormState>(emptyForm); const [saving,setSaving]=useState(false); const [uploading,setUploading]=useState(false); const [previews,setPreviews]=useState<string[]>([]);

  const load=useCallback(async()=>{setLoading(true);setError('');try{const {data}=await api.get('/admin/products',{params:{page,limit:20,search:search||undefined,category:category||undefined,status:status||undefined,sort}});setProducts(data.data);setPages(data.pagination.pages||1);setTotal(data.pagination.total);}catch(e){setError('Không thể tải danh sách sản phẩm.');}finally{setLoading(false);}},[page,search,category,status,sort]);
  useEffect(()=>{api.get('/admin/products/filters').then(({data})=>setFilters(data.data)).catch(()=>toast.error('Không thể tải bộ lọc'));},[]);
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer);},[load]);
  useEffect(()=>()=>previews.forEach(URL.revokeObjectURL),[previews]);

  const openNew=()=>{setEditing({id:0} as Product);setForm(emptyForm);setPreviews([]);};
  const openEdit=async(product:Product)=>{try{const {data}=await api.get(`/admin/products/${product.id}`);const p=data.data as Product & {category_id:number;brand_id:number|null};setEditing(p);setForm({product_name:p.product_name,description:p.description||'',sku:p.display_variant.sku,price:String(p.display_variant.price),sale_price:p.display_variant.sale_price==null?'':String(p.display_variant.sale_price),stock:String(p.display_variant.available),category_id:String(p.category_id),brand_id:p.brand_id?String(p.brand_id):'',is_active:Boolean(p.is_active),is_featured:Boolean(p.is_featured),is_on_sale:Boolean(p.is_on_sale)});setPreviews([]);}catch{toast.error('Không thể tải sản phẩm');}};
  const payload=()=>({product_name:form.product_name.trim(),description:form.description.trim()||null,sku:form.sku.trim(),price:Number(form.price),sale_price:form.sale_price===''?null:Number(form.sale_price),stock:Number(form.stock),category_id:Number(form.category_id),brand_id:form.brand_id?Number(form.brand_id):null,is_active:form.is_active,is_featured:form.is_featured,is_on_sale:form.is_on_sale});
  const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{if(editing?.id){await api.patch(`/admin/products/${editing.id}`,payload());toast.success('Đã cập nhật sản phẩm');await openEdit(editing);}else{const {data}=await api.post('/admin/products',payload());toast.success('Đã tạo sản phẩm');await openEdit(data.data);}await load();}catch(e:any){toast.error(e.response?.data?.message||'Không thể lưu sản phẩm');}finally{setSaving(false);}};
  const remove=async(product:Product)=>{if(!confirm(`Xóa sản phẩm “${product.product_name}”? Thao tác này không thể hoàn tác.`))return;try{await api.delete(`/admin/products/${product.id}`);toast.success('Đã xóa sản phẩm');if(editing?.id===product.id)setEditing(null);load();}catch(e:any){toast.error(e.response?.data?.message||'Không thể xóa sản phẩm');}};
  const upload=async(e:ChangeEvent<HTMLInputElement>)=>{if(!editing?.id||!e.target.files?.length)return;const files=Array.from(e.target.files);setPreviews(files.map(URL.createObjectURL));setUploading(true);try{const body=new FormData();files.forEach(file=>body.append('images',file));const {data}=await api.post(`/admin/products/${editing.id}/images`,body);setEditing(data.data);toast.success(`Đã tải lên ${files.length} ảnh`);load();}catch(e:any){toast.error(e.response?.data?.message||'Upload thất bại');}finally{setUploading(false);e.target.value='';}};
  const imageAction=async(imageId:number,action:'primary'|'delete')=>{if(!editing?.id)return;if(action==='delete'&&!confirm('Xóa ảnh này?'))return;setUploading(true);try{const {data}=action==='primary'?await api.patch(`/admin/products/${editing.id}/images/${imageId}/primary`):await api.delete(`/admin/products/${editing.id}/images/${imageId}`);setEditing(data.data);toast.success(action==='primary'?'Đã đổi ảnh đại diện':'Đã xóa ảnh');load();}catch(e:any){toast.error(e.response?.data?.message||'Thao tác thất bại');}finally{setUploading(false);}};
  const field=(key:keyof FormState,value:string|boolean)=>setForm(prev=>({...prev,[key]:value}));

  return <div className="p-4 md:p-8 space-y-6">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Quản lý sản phẩm</h1><p className="text-sm text-slate-400">{total} sản phẩm</p></div><button onClick={openNew} className="btn-primary flex items-center justify-center gap-2"><Plus size={18}/>Thêm sản phẩm</button></div>
    <div className="grid grid-cols-1 md:grid-cols-4 gap-3 bg-slate-900 border border-slate-800 p-4 rounded-xl"><label className="relative"><Search className="absolute left-3 top-3 text-slate-500" size={17}/><input aria-label="Tìm sản phẩm" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Tên hoặc SKU" className="input-field pl-10 w-full"/></label><select aria-label="Danh mục" className="input-field" value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="">Mọi danh mục</option>{filters.categories.map(c=><option key={c.id} value={c.slug}>{c.name}</option>)}</select><select aria-label="Trạng thái" className="input-field" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Mọi trạng thái</option><option value="active">Đang bán</option><option value="inactive">Tạm ẩn</option></select><select aria-label="Sắp xếp" className="input-field" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated_desc">Mới cập nhật</option><option value="created_desc">Mới tạo</option><option value="name_asc">Tên A–Z</option><option value="name_desc">Tên Z–A</option><option value="price_asc">Giá tăng</option><option value="price_desc">Giá giảm</option></select></div>
    {error?<div className="rounded-xl border border-red-500/30 bg-red-500/10 p-6 text-red-300">{error}<button onClick={load} className="ml-3 underline">Thử lại</button></div>:loading?<div className="p-12 text-center text-slate-400">Đang tải…</div>:products.length===0?<div className="p-12 text-center text-slate-400 border border-slate-800 rounded-xl">Không có sản phẩm phù hợp.</div>:<div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-900 text-slate-400"><tr><th className="p-3 text-left">Ảnh</th><th className="p-3 text-left">Sản phẩm</th><th className="p-3 text-left">Danh mục</th><th className="p-3 text-right">Giá</th><th className="p-3 text-right">Tồn</th><th className="p-3">Trạng thái</th><th className="p-3 text-right">Thao tác</th></tr></thead><tbody>{products.map(p=><tr key={p.id} className="border-t border-slate-800 hover:bg-slate-900/50"><td className="p-3"><ProductImage src={p.primary_image?.image_url} alt={p.product_name} className="w-14 h-14 object-cover rounded-lg"/></td><td className="p-3"><div className="font-medium">{p.product_name}</div><div className="text-xs text-slate-500">#{p.id} · {p.display_variant?.sku||p.sku}</div></td><td className="p-3 text-slate-300">{p.category}</td><td className="p-3 text-right">{Number(p.display_variant?.price||p.price).toLocaleString('vi-VN')} ₫</td><td className="p-3 text-right">{p.display_variant?.available??p.stock}</td><td className="p-3 text-center"><span className={p.is_active?'text-green-400':'text-slate-500'}>{p.is_active?'Đang bán':'Tạm ẩn'}</span></td><td className="p-3"><div className="flex justify-end gap-2"><button aria-label={`Sửa ${p.product_name}`} onClick={()=>openEdit(p)} className="btn-ghost p-2"><Edit3 size={16}/></button><button aria-label={`Xóa ${p.product_name}`} onClick={()=>remove(p)} className="btn-ghost p-2 text-red-400"><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>}
    <div className="flex justify-between items-center"><span className="text-sm text-slate-500">Trang {page}/{pages}</span><div className="flex gap-2"><button className="btn-secondary" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Trước</button><button className="btn-secondary" disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Sau</button></div></div>
    {editing&&<div className="fixed inset-0 z-50 bg-black/70 flex justify-end" onMouseDown={e=>{if(e.target===e.currentTarget)setEditing(null)}}><div className="w-full max-w-3xl h-full overflow-y-auto bg-slate-950 border-l border-slate-800 p-5 md:p-8"><div className="flex justify-between mb-6"><h2 className="text-xl font-bold">{editing.id?'Sửa sản phẩm':'Thêm sản phẩm'}</h2><button onClick={()=>setEditing(null)}><X/></button></div><form onSubmit={submit} className="grid grid-cols-1 sm:grid-cols-2 gap-4"><label className="sm:col-span-2">Tên sản phẩm<input required maxLength={200} className="input-field w-full mt-1" value={form.product_name} onChange={e=>field('product_name',e.target.value)}/></label><label>SKU<input required maxLength={100} className="input-field w-full mt-1" value={form.sku} onChange={e=>field('sku',e.target.value)}/></label><label>Danh mục<select required className="input-field w-full mt-1" value={form.category_id} onChange={e=>field('category_id',e.target.value)}><option value="">Chọn danh mục</option>{filters.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Giá<input required min="0.01" step="0.01" type="number" className="input-field w-full mt-1" value={form.price} onChange={e=>field('price',e.target.value)}/></label><label>Giá khuyến mãi<input min="0" step="0.01" type="number" className="input-field w-full mt-1" value={form.sale_price} onChange={e=>field('sale_price',e.target.value)}/></label><label>Tồn kho<input required min="0" step="1" type="number" className="input-field w-full mt-1" value={form.stock} onChange={e=>field('stock',e.target.value)}/></label><label>Thương hiệu<select className="input-field w-full mt-1" value={form.brand_id} onChange={e=>field('brand_id',e.target.value)}><option value="">Không có</option>{filters.brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="sm:col-span-2">Mô tả<textarea rows={4} className="input-field w-full mt-1" value={form.description} onChange={e=>field('description',e.target.value)}/></label><div className="sm:col-span-2 flex flex-wrap gap-5">{(['is_active','is_featured','is_on_sale'] as const).map((key,i)=><label key={key} className="flex gap-2"><input type="checkbox" checked={form[key]} onChange={e=>field(key,e.target.checked)}/>{['Đang bán','Nổi bật','Khuyến mãi'][i]}</label>)}</div><button disabled={saving} className="btn-primary sm:col-span-2">{saving?'Đang lưu…':'Lưu sản phẩm'}</button></form>
      {editing.id>0&&<section className="mt-8 pt-8 border-t border-slate-800"><div className="flex items-center justify-between"><div><h3 className="font-bold">Hình ảnh</h3><p className="text-xs text-slate-500">JPEG, PNG, WebP · tối đa 5 MB/ảnh · 8 ảnh</p></div><label className="btn-secondary flex items-center gap-2 cursor-pointer"><ImagePlus size={17}/>{uploading?'Đang tải…':'Chọn ảnh'}<input hidden type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={upload}/></label></div>{previews.length>0&&<div className="grid grid-cols-4 gap-2 mt-4">{previews.map(src=><ProductImage key={src} src={src} className="aspect-square object-cover rounded-lg opacity-60" alt="Xem trước"/>)}</div>}<div className="grid grid-cols-2 sm:grid-cols-3 gap-3 mt-4">{(editing.images||[]).map(image=><div key={image.id} className="relative border border-slate-800 rounded-xl overflow-hidden"><ProductImage src={image.image_url} className="aspect-square object-cover w-full" alt={editing.product_name}/>{image.is_primary&&<span className="absolute top-2 left-2 bg-orange-500 text-white text-xs px-2 py-1 rounded">Đại diện</span>}<div className="flex gap-1 p-2"><button disabled={uploading||image.is_primary} onClick={()=>imageAction(image.id,'primary')} className="btn-ghost flex-1 text-xs"><Star size={13}/> Chọn</button><button disabled={uploading} onClick={()=>imageAction(image.id,'delete')} className="btn-ghost text-red-400 p-2"><Trash2 size={14}/></button></div></div>)}</div>{(editing.images||[]).length===0&&<p className="text-slate-500 text-sm mt-4">Chưa có ảnh; giao diện đang dùng ảnh dự phòng.</p>}</section>}</div></div>}
  </div>;
}
