import { useCallback,useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import { AxiosError } from 'axios';
import toast from 'react-hot-toast';
import { RefreshCw } from 'lucide-react';
import { adminOrdersApi } from '../../services/adminOrdersApi';
import type { AdminOrderFilters,AdminOrderListItem,OrderSortField,OrderStatus,PaymentStatus } from '../../types/adminOrders';

const defaults:AdminOrderFilters={search:'',orderStatus:'',paymentStatus:'',userId:'',dateFrom:'',dateTo:'',sortBy:'created_at',sortOrder:'desc',page:1,limit:20};
const statuses:OrderStatus[]=['PENDING','CONFIRMED','PROCESSING','SHIPPED','DELIVERED','CANCELLED'];
const payments:PaymentStatus[]=['UNPAID','PENDING','PAID','FAILED','PARTIALLY_REFUNDED','REFUNDED'];
const errorMessage=(error:unknown)=>error instanceof AxiosError&&typeof error.response?.data?.message==='string'?error.response.data.message:'Unable to load orders';
const money=(value:number,currency:string)=>`${value.toFixed(2)} ${currency}`;

export default function AdminOrdersPage(){
 const[filters,setFilters]=useState<AdminOrderFilters>(defaults),[rows,setRows]=useState<AdminOrderListItem[]>([]),[pageInfo,setPageInfo]=useState({page:1,limit:20,total:0,totalPages:1}),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await adminOrdersApi.listAdminOrders(filters);setRows(response.data.data.items);setPageInfo(response.data.data);}catch(e){setError(errorMessage(e))}finally{setLoading(false)}},[filters]);
 useEffect(()=>{void load()},[load]);
 const update=<K extends keyof AdminOrderFilters>(key:K,value:AdminOrderFilters[K])=>setFilters(current=>({...current,[key]:value,page:key==='page'?Number(value):1}));
 const reset=()=>setFilters(defaults);
 return <div className="space-y-5 p-4 md:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Orders</h1><p className="text-sm text-slate-400">{pageInfo.total} records</p></div><button type="button" className="btn-secondary flex items-center gap-2" aria-label="Refresh orders" title="Refresh orders" disabled={loading} onClick={()=>void load()}><RefreshCw size={16} aria-hidden="true" className={loading?'animate-spin':''}/>Refresh</button></div>
 <div className="grid gap-3 rounded-xl border border-slate-800 bg-slate-950 p-4 sm:grid-cols-2 lg:grid-cols-4"><label>Search<input aria-label="Search orders" className="input-field mt-1 w-full" value={filters.search} onChange={e=>update('search',e.target.value)} placeholder="Order/customer/payment reference"/></label><label>Order status<select aria-label="Order status filter" className="input-field mt-1 w-full" value={filters.orderStatus} onChange={e=>update('orderStatus',e.target.value as AdminOrderFilters['orderStatus'])}><option value="">All</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Payment status<select aria-label="Payment status filter" className="input-field mt-1 w-full" value={filters.paymentStatus} onChange={e=>update('paymentStatus',e.target.value as AdminOrderFilters['paymentStatus'])}><option value="">All</option>{payments.map(s=><option key={s}>{s}</option>)}</select></label><label>User ID<input aria-label="User ID filter" type="number" min="1" className="input-field mt-1 w-full" value={filters.userId} onChange={e=>update('userId',e.target.value)}/></label><label>Date from<input aria-label="Date from" type="date" max={filters.dateTo||undefined} className="input-field mt-1 w-full" value={filters.dateFrom} onChange={e=>update('dateFrom',e.target.value)}/></label><label>Date to<input aria-label="Date to" type="date" min={filters.dateFrom||undefined} className="input-field mt-1 w-full" value={filters.dateTo} onChange={e=>update('dateTo',e.target.value)}/></label><label>Sort by<select aria-label="Sort orders by" className="input-field mt-1 w-full" value={filters.sortBy} onChange={e=>update('sortBy',e.target.value as OrderSortField)}>{['order_number','customer_name','total_amount','order_status','payment_status','created_at','updated_at'].map(s=><option key={s}>{s}</option>)}</select></label><label>Sort order<select aria-label="Order sort direction" className="input-field mt-1 w-full" value={filters.sortOrder} onChange={e=>update('sortOrder',e.target.value as 'asc'|'desc')}><option value="asc">Ascending</option><option value="desc">Descending</option></select></label><label>Page size<select aria-label="Order page size" className="input-field mt-1 w-full" value={filters.limit} onChange={e=>update('limit',Number(e.target.value) as AdminOrderFilters['limit'])}>{[10,20,50,100].map(s=><option key={s}>{s}</option>)}</select></label><button type="button" className="btn-secondary self-end" onClick={reset}>Reset</button></div>
 {error?<div role="alert" className="rounded-xl border border-red-500/30 bg-red-500/10 p-5 text-red-300">{error}<button type="button" className="ml-3 underline" onClick={()=>void load()}>Retry</button></div>:loading?<div className="p-10 text-center text-slate-400">Loading orders…</div>:rows.length===0?<div className="rounded-xl border border-slate-800 p-10 text-center text-slate-400">No orders match these filters.</div>:<div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full min-w-[1100px] text-sm"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Order status</th><th>Payment status</th><th>Created</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t border-slate-800"><td className="p-3"><Link className="text-blue-400" to={`/admin/orders/${row.id}`}>{row.orderNumber}</Link><div className="text-xs text-slate-500">#{row.id}</div></td><td><div>{row.customerName}</div><div className="text-xs text-slate-400">{row.customerEmail}</div></td><td>{row.itemCount}</td><td>{money(row.totalAmount,row.currency)}</td><td>{row.orderStatus}</td><td>{row.paymentStatus}</td><td>{new Date(row.createdAt).toLocaleString()}</td><td>{new Date(row.updatedAt).toLocaleString()}</td><td><Link className="text-blue-400" to={`/admin/orders/${row.id}`}>View details</Link></td></tr>)}</tbody></table></div>}
 <div className="flex flex-wrap items-center justify-between gap-3"><span>Page {pageInfo.page} of {Math.max(1,pageInfo.totalPages)}</span><div className="flex gap-2"><button type="button" className="btn-secondary" disabled={loading||filters.page<=1} onClick={()=>update('page',filters.page-1)}>Previous</button><button type="button" className="btn-secondary" disabled={loading||filters.page>=Math.max(1,pageInfo.totalPages)} onClick={()=>update('page',filters.page+1)}>Next</button></div></div></div>
}
