import { ChangeEvent, FormEvent, useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Edit3, ImagePlus, Plus, Search, Star, Trash2, X } from 'lucide-react';
import toast from 'react-hot-toast';
import api from '../../api/axios';
import ProductImage from '../../components/products/ProductImage';
import type { Product } from '../../types/product';

interface Choice { id:number; name:string; slug:string }
interface Filters { categories:Choice[]; brands:Choice[] }
interface FormState { product_name:string; description:string; sku:string; price:string; sale_price:string; stock:string; category_id:string; brand_id:string; is_active:boolean; is_featured:boolean; is_on_sale:boolean }
const emptyForm: FormState = { product_name:'',description:'',sku:'',price:'',sale_price:'',stock:'0',category_id:'',brand_id:'',is_active:true,is_featured:false,is_on_sale:false };

export default function AdminProductsPage() {
  const [products,setProducts]=useState<Product[]>([]); const [filters,setFilters]=useState<Filters>({categories:[],brands:[]});
  const [page,setPage]=useState(1); const [pages,setPages]=useState(1); const [total,setTotal]=useState(0); const [search,setSearch]=useState(''); const [category,setCategory]=useState(''); const [status,setStatus]=useState(''); const [sort,setSort]=useState('updated_desc');
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [editing,setEditing]=useState<Product|null>(null); const [form,setForm]=useState<FormState>(emptyForm); const [saving,setSaving]=useState(false); const [uploading,setUploading]=useState(false); const [previews,setPreviews]=useState<string[]>([]);

  const load=useCallback(async()=>{setLoading(true);setError('');try{const {data}=await api.get('/admin/products',{params:{page,limit:20,search:search||undefined,category:category||undefined,status:status||undefined,sort}});setProducts(data.data);setPages(data.pagination.pages||1);setTotal(data.pagination.total);}catch(e){setError('KhÃ´ng thá»ƒ táº£i danh sÃ¡ch sáº£n pháº©m.');}finally{setLoading(false);}},[page,search,category,status,sort]);
  useEffect(()=>{api.get('/admin/products/filters').then(({data})=>setFilters(data.data)).catch(()=>toast.error('KhÃ´ng thá»ƒ táº£i bá»™ lá»c'));},[]);
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer);},[load]);
  useEffect(()=>()=>previews.forEach(URL.revokeObjectURL),[previews]);

  const openNew=()=>{setEditing({id:0} as Product);setForm(emptyForm);setPreviews([]);};
  const openEdit=async(product:Product)=>{try{const {data}=await api.get(`/admin/products/${product.id}`);const p=data.data as Product & {category_id:number;brand_id:number|null};setEditing(p);setForm({product_name:p.product_name,description:p.description||'',sku:p.display_variant.sku,price:String(p.display_variant.price),sale_price:p.display_variant.sale_price==null?'':String(p.display_variant.sale_price),stock:String(p.display_variant.available),category_id:String(p.category_id),brand_id:p.brand_id?String(p.brand_id):'',is_active:Boolean(p.is_active),is_featured:Boolean(p.is_featured),is_on_sale:Boolean(p.is_on_sale)});setPreviews([]);}catch{toast.error('KhÃ´ng thá»ƒ táº£i sáº£n pháº©m');}};
  const payload=()=>({product_name:form.product_name.trim(),description:form.description.trim()||null,sku:form.sku.trim(),price:Number(form.price),sale_price:form.sale_price===''?null:Number(form.sale_price),...(!editing?.id?{stock:Number(form.stock)}:{}),category_id:Number(form.category_id),brand_id:form.brand_id?Number(form.brand_id):null,is_active:form.is_active,is_featured:form.is_featured,is_on_sale:form.is_on_sale});
  const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{if(editing?.id){await api.patch(`/admin/products/${editing.id}`,payload());toast.success('ÄÃ£ cáº­p nháº­t sáº£n pháº©m');await openEdit(editing);}else{const {data}=await api.post('/admin/products',payload());toast.success('ÄÃ£ táº¡o sáº£n pháº©m');await openEdit(data.data);}await load();}catch(e:any){toast.error(e.response?.data?.message||'KhÃ´ng thá»ƒ lÆ°u sáº£n pháº©m');}finally{setSaving(false);}};
  const remove=async(product:Product)=>{if(!confirm(`XÃ³a sáº£n pháº©m â€œ${product.product_name}â€? Thao tÃ¡c nÃ y khÃ´ng thá»ƒ hoÃ n tÃ¡c.`))return;try{await api.delete(`/admin/products/${product.id}`);toast.success('ÄÃ£ xÃ³a sáº£n pháº©m');if(editing?.id===product.id)setEditing(null);load();}catch(e:any){toast.error(e.response?.data?.message||'KhÃ´ng thá»ƒ xÃ³a sáº£n pháº©m');}};
  const upload=async(e:ChangeEvent<HTMLInputElement>)=>{if(!editing?.id||!e.target.files?.length)return;const files=Array.from(e.target.files);setPreviews(files.map(URL.createObjectURL));setUploading(true);try{const body=new FormData();files.forEach(file=>body.append('images',file));const {data}=await api.post(`/admin/products/${editing.id}/images`,body);setEditing(data.data);toast.success(`ÄÃ£ táº£i lÃªn ${files.length} áº£nh`);load();}catch(e:any){toast.error(e.response?.data?.message||'Upload tháº¥t báº¡i');}finally{setUploading(false);e.target.value='';}};
  const imageAction=async(imageId:number,action:'primary'|'delete')=>{if(!editing?.id)return;if(action==='delete'&&!confirm('XÃ³a áº£nh nÃ y?'))return;setUploading(true);try{const {data}=action==='primary'?await api.patch(`/admin/products/${editing.id}/images/${imageId}/primary`):await api.delete(`/admin/products/${editing.id}/images/${imageId}`);setEditing(data.data);toast.success(action==='primary'?'ÄÃ£ Ä‘á»•i áº£nh Ä‘áº¡i diá»‡n':'ÄÃ£ xÃ³a áº£nh');load();}catch(e:any){toast.error(e.response?.data?.message||'Thao tÃ¡c tháº¥t báº¡i');}finally{setUploading(false);}};
  const field=(key:keyof FormState,value:string|boolean)=>setForm(prev=>({...prev,[key]:value}));

  return <div className="p-4 md:p-8 space-y-6">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Quáº£n lÃ½ sáº£n pháº©m</h1><p className="text-sm text-slate-400">{total} sáº£n pháº©m</p></div><button onClick={openNew} className="btn-primary flex items-center justify-center gap-2"><Plus size={18}/>ThÃªm sáº£n pháº©m</button></div>
    <div className="grid grid-cols-1 md:grid-cols-4 gap-3 bg-slate-900 border border-slate-800 p-4 rounded-xl"><label className="relative"><Search className="absolute left-3 top-3 text-slate-500" size={17}/><input aria-label="TÃ¬m sáº£n pháº©m" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="TÃªn hoáº·c SKU" className="input-field pl-10 w-full"/></label><select aria-label="Danh má»¥c" className="input-field" value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="">Má»i danh má»¥c</option>{filters.categories.map(c=><option key={c.id} value={c.slug}>{c.name}</option>)}</select><select aria-label="Tráº¡ng thÃ¡i" className="input-field" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Má»i tráº¡ng thÃ¡i</option><option value="active">Äang bÃ¡n</option><option value="inactive">Táº¡m áº©n</option></select><select aria-label="Sáº¯p xáº¿p" className="input-field" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated_desc">Má»›i cáº­p nháº­t</option><option value="created_desc">Má»›i táº¡o</option><option value="name_asc">TÃªn Aâ€“Z</option><option value="name_desc">TÃªn Zâ€“A</option><option value="price_asc">GiÃ¡ tÄƒng</option><option value="price_desc">GiÃ¡ giáº£m</option></select></div>
    {error?<div className="rounded-xl border border-red-500/30 bg-red-500/10 p-6 text-red-300">{error}<button onClick={load} className="ml-3 underline">Thá»­ láº¡i</button></div>:loading?<div className="p-12 text-center text-slate-400">Äang táº£iâ€¦</div>:products.length===0?<div className="p-12 text-center text-slate-400 border border-slate-800 rounded-xl">KhÃ´ng cÃ³ sáº£n pháº©m phÃ¹ há»£p.</div>:<div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-900 text-slate-400"><tr><th className="p-3 text-left">áº¢nh</th><th className="p-3 text-left">Sáº£n pháº©m</th><th className="p-3 text-left">Danh má»¥c</th><th className="p-3 text-right">GiÃ¡</th><th className="p-3 text-right">Tá»“n</th><th className="p-3">Tráº¡ng thÃ¡i</th><th className="p-3 text-right">Thao tÃ¡c</th></tr></thead><tbody>{products.map(p=><tr key={p.id} className="border-t border-slate-800 hover:bg-slate-900/50"><td className="p-3"><ProductImage src={p.primary_image?.image_url} alt={p.product_name} className="w-14 h-14 object-cover rounded-lg"/></td><td className="p-3"><div className="font-medium">{p.product_name}</div><Link to={`/admin/products/${p.id}/variants`} className="text-xs text-blue-400 hover:underline">Manage Variants</Link><div className="text-xs text-slate-500">#{p.id} Â· {p.display_variant?.sku||p.sku}</div></td><td className="p-3 text-slate-300">{p.category}</td><td className="p-3 text-right">{Number(p.display_variant?.price||p.price).toLocaleString('vi-VN')} â‚«</td><td className="p-3 text-right">{p.display_variant?.available??p.stock}</td><td className="p-3 text-center"><span className={p.is_active?'text-green-400':'text-slate-500'}>{p.is_active?'Äang bÃ¡n':'Táº¡m áº©n'}</span></td><td className="p-3"><div className="flex justify-end gap-2"><button aria-label={`Sá»­a ${p.product_name}`} onClick={()=>openEdit(p)} className="btn-ghost p-2"><Edit3 size={16}/></button><button aria-label={`XÃ³a ${p.product_name}`} onClick={()=>remove(p)} className="btn-ghost p-2 text-red-400"><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>}
    <div className="flex justify-between items-center"><span className="text-sm text-slate-500">Trang {page}/{pages}</span><div className="flex gap-2"><button className="btn-secondary" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>TrÆ°á»›c</button><button className="btn-secondary" disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Sau</button></div></div>
    {editing&&<div className="fixed inset-0 z-50 bg-black/70 flex justify-end" onMouseDown={e=>{if(e.target===e.currentTarget)setEditing(null)}}><div className="w-full max-w-3xl h-full overflow-y-auto bg-slate-950 border-l border-slate-800 p-5 md:p-8"><div className="flex justify-between mb-6"><h2 className="text-xl font-bold">{editing.id?'Sá»­a sáº£n pháº©m':'ThÃªm sáº£n pháº©m'}</h2><button onClick={()=>setEditing(null)}><X/></button></div><form onSubmit={submit} className="grid grid-cols-1 sm:grid-cols-2 gap-4"><label className="sm:col-span-2">TÃªn sáº£n pháº©m<input required maxLength={200} className="input-field w-full mt-1" value={form.product_name} onChange={e=>field('product_name',e.target.value)}/></label><label>SKU<input required maxLength={100} className="input-field w-full mt-1" value={form.sku} onChange={e=>field('sku',e.target.value)}/></label><label>Danh má»¥c<select required className="input-field w-full mt-1" value={form.category_id} onChange={e=>field('category_id',e.target.value)}><option value="">Chá»n danh má»¥c</option>{filters.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>GiÃ¡<input required min="0.01" step="0.01" type="number" className="input-field w-full mt-1" value={form.price} onChange={e=>field('price',e.target.value)}/></label><label>GiÃ¡ khuyáº¿n mÃ£i<input min="0" step="0.01" type="number" className="input-field w-full mt-1" value={form.sale_price} onChange={e=>field('sale_price',e.target.value)}/></label><label>Tá»“n kho<input required min="0" step="1" type="number" className="input-field w-full mt-1" value={form.stock} onChange={e=>field('stock',e.target.value)}/></label><label>ThÆ°Æ¡ng hiá»‡u<select className="input-field w-full mt-1" value={form.brand_id} onChange={e=>field('brand_id',e.target.value)}><option value="">KhÃ´ng cÃ³</option>{filters.brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="sm:col-span-2">MÃ´ táº£<textarea rows={4} className="input-field w-full mt-1" value={form.description} onChange={e=>field('description',e.target.value)}/></label><div className="sm:col-span-2 flex flex-wrap gap-5">{(['is_active','is_featured','is_on_sale'] as const).map((key,i)=><label key={key} className="flex gap-2"><input type="checkbox" checked={form[key]} onChange={e=>field(key,e.target.checked)}/>{['Äang bÃ¡n','Ná»•i báº­t','Khuyáº¿n mÃ£i'][i]}</label>)}</div><button disabled={saving} className="btn-primary sm:col-span-2">{saving?'Äang lÆ°uâ€¦':'LÆ°u sáº£n pháº©m'}</button></form>
      {editing.id>0&&<section className="mt-8 pt-8 border-t border-slate-800"><div className="flex items-center justify-between"><div><h3 className="font-bold">HÃ¬nh áº£nh</h3><p className="text-xs text-slate-500">JPEG, PNG, WebP Â· tá»‘i Ä‘a 5 MB/áº£nh Â· 8 áº£nh</p></div><label className="btn-secondary flex items-center gap-2 cursor-pointer"><ImagePlus size={17}/>{uploading?'Äang táº£iâ€¦':'Chá»n áº£nh'}<input hidden type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={upload}/></label></div>{previews.length>0&&<div className="grid grid-cols-4 gap-2 mt-4">{previews.map(src=><ProductImage key={src} src={src} className="aspect-square object-cover rounded-lg opacity-60" alt="Xem trÆ°á»›c"/>)}</div>}<div className="grid grid-cols-2 sm:grid-cols-3 gap-3 mt-4">{(editing.images||[]).map(image=><div key={image.id} className="relative border border-slate-800 rounded-xl overflow-hidden"><ProductImage src={image.image_url} className="aspect-square object-cover w-full" alt={editing.product_name}/>{image.is_primary&&<span className="absolute top-2 left-2 bg-orange-500 text-white text-xs px-2 py-1 rounded">Äáº¡i diá»‡n</span>}<div className="flex gap-1 p-2"><button disabled={uploading||image.is_primary} onClick={()=>imageAction(image.id,'primary')} className="btn-ghost flex-1 text-xs"><Star size={13}/> Chá»n</button><button disabled={uploading} onClick={()=>imageAction(image.id,'delete')} className="btn-ghost text-red-400 p-2"><Trash2 size={14}/></button></div></div>)}</div>{(editing.images||[]).length===0&&<p className="text-slate-500 text-sm mt-4">ChÆ°a cÃ³ áº£nh; giao diá»‡n Ä‘ang dÃ¹ng áº£nh dá»± phÃ²ng.</p>}</section>}</div></div>}
  </div>;
}
