import { FormEvent,useCallback,useEffect,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { AxiosError } from 'axios';
import toast from 'react-hot-toast';
import { RefreshCw,X } from 'lucide-react';
import { adminOrdersApi } from '../../services/adminOrdersApi';
import type { AdminOrderDetail,AdminPaymentConfigurationStatus,AdminPaymentStatusInput,OrderStatus,PaymentStatus } from '../../types/adminOrders';
const nextStatuses:Record<OrderStatus,OrderStatus[]>={PENDING:['CONFIRMED','CANCELLED'],CONFIRMED:['PROCESSING','CANCELLED'],PROCESSING:['SHIPPED','CANCELLED'],SHIPPED:['DELIVERED'],DELIVERED:[],CANCELLED:[]};
const errorMessage=(error:unknown)=>error instanceof AxiosError&&typeof error.response?.data?.message==='string'?error.response.data.message:'Operation failed';
const money=(value:number,currency:string)=>`${value.toFixed(2)} ${currency}`;
export default function AdminOrderDetailPage(){
 const id=Number(useParams().orderId),[order,setOrder]=useState<AdminOrderDetail|null>(null),[configuration,setConfiguration]=useState<AdminPaymentConfigurationStatus|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[dialog,setDialog]=useState(false),[newStatus,setNewStatus]=useState<OrderStatus>('PENDING'),[paymentDialog,setPaymentDialog]=useState(false),[newPaymentStatus,setNewPaymentStatus]=useState<AdminPaymentStatusInput['status']>('PAID'),[note,setNote]=useState(''),[paymentNoteError,setPaymentNoteError]=useState(''),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{setOrder((await adminOrdersApi.getAdminOrder(id)).data.data)}catch(e){setError(errorMessage(e))}finally{setLoading(false)}},[id]);useEffect(()=>{void load()},[load]);
 useEffect(()=>{void adminOrdersApi.getPaymentConfiguration().then(response=>setConfiguration(response.data.data)).catch(()=>setConfiguration(null));},[]);
 const allowedOrderStatuses=order?nextStatuses[order.orderStatus].filter(status=>status!=='CANCELLED'||!['PENDING','PAID','PARTIALLY_REFUNDED'].includes(order.paymentStatus)):[];
 const openStatus=()=>{if(!order||allowedOrderStatuses.length===0)return;setNewStatus(allowedOrderStatuses[0]);setNote('');setDialog(true)};
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!order||saving)return;setSaving(true);try{const updated=(await adminOrdersApi.updateAdminOrderStatus(order.id,{status:newStatus,note:note.trim()||undefined})).data.data;setOrder(updated);setDialog(false);setNote('');toast.success('Order status updated')}catch(e){toast.error(errorMessage(e))}finally{setSaving(false)}};
 const paymentOptions:Record<PaymentStatus,AdminPaymentStatusInput['status'][]>= {UNPAID:['PAID'],PENDING:['PAID','FAILED'],FAILED:['UNPAID'],PAID:['REFUNDED'],PARTIALLY_REFUNDED:[],REFUNDED:[]};
 const paymentNoteRequired=Boolean(order&&(newPaymentStatus==='FAILED'||newPaymentStatus==='UNPAID'||newPaymentStatus==='REFUNDED'||(order.paymentStatus==='UNPAID'&&newPaymentStatus==='PAID')));
 const openPayment=()=>{if(!order||paymentOptions[order.paymentStatus].length===0)return;setNewPaymentStatus(paymentOptions[order.paymentStatus][0]);setNote('');setPaymentNoteError('');setPaymentDialog(true)};
 const submitPayment=async(e:FormEvent)=>{e.preventDefault();if(!order||saving)return;if(paymentNoteRequired&&!note.trim()){setPaymentNoteError('Note is required for this payment transition.');return}setPaymentNoteError('');setSaving(true);try{const result=(await adminOrdersApi.updateAdminOrderPaymentStatus(order.id,{status:newPaymentStatus,note:note.trim()||undefined})).data.data;setPaymentDialog(false);setNote('');await load();toast.success(newPaymentStatus==='PAID'?'Payment confirmed.':newPaymentStatus==='FAILED'?'Payment marked as failed.':newPaymentStatus==='REFUNDED'?'Refund confirmed.':'Payment reset to unpaid.');if(!result.emailSent&&(newPaymentStatus==='PAID'||newPaymentStatus==='FAILED'||newPaymentStatus==='REFUNDED'))toast.error('Payment status was updated, but the customer email could not be sent.')}catch(e){toast.error(errorMessage(e))}finally{setSaving(false)}};
 if(loading)return <div className="p-8 text-center text-slate-400">Loading order…</div>;
 if(error||!order)return <div className="space-y-4 p-8"><Link className="text-blue-400" to="/admin/orders">Back to Orders</Link><div role="alert" className="rounded-xl border border-red-500/30 bg-red-500/10 p-5 text-red-300">{error||'Order not found'}<button type="button" className="ml-3 underline" onClick={()=>void load()}>Retry</button></div></div>;
 return <div className="space-y-5 p-4 md:p-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link className="text-blue-400" to="/admin/orders">Back to Orders</Link><h1 className="mt-2 text-2xl font-bold">{order.orderNumber}</h1><p className="text-sm text-slate-400">Order ID: {order.id}</p>{order.paymentStatus==='PAID'&&<p className="mt-2 text-amber-300">Hoàn tiền trước khi hủy đơn.</p>}</div><div className="flex gap-2"><button type="button" className="btn-secondary flex items-center gap-2" aria-label="Refresh order" disabled={loading} onClick={()=>void load()}><RefreshCw size={16} aria-hidden="true"/>Refresh</button>{paymentOptions[order.paymentStatus].length>0&&<button type="button" className="btn-primary" onClick={openPayment}>Update payment status</button>}{allowedOrderStatuses.length>0&&<button type="button" className="btn-primary" onClick={openStatus}>Update status</button>}</div></div>
 <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-xl border border-slate-800 bg-slate-950 p-5"><h2 className="mb-3 text-lg font-semibold">Order summary</h2><p>Order status: <strong>{order.orderStatus}</strong></p><p>Payment status: <strong>{order.paymentStatus}</strong></p><p>Created: {new Date(order.createdAt).toLocaleString()}</p><p>Updated: {new Date(order.updatedAt).toLocaleString()}</p></section><section className="rounded-xl border border-slate-800 bg-slate-950 p-5"><h2 className="mb-3 text-lg font-semibold">Customer</h2><p>{order.customer.name}</p><p>{order.customer.email}</p><p>{order.customer.phone||'—'}</p><p>User ID: {order.userId}</p></section><section className="rounded-xl border border-slate-800 bg-slate-950 p-5"><h2 className="mb-3 text-lg font-semibold">Shipping</h2><p>{order.shipping.addressLine1||'—'}</p><p>{order.shipping.addressLine2||'—'}</p><p>{[order.shipping.city,order.shipping.state,order.shipping.postalCode].filter(Boolean).join(', ')||'—'}</p><p>{order.shipping.country||'—'}</p></section><section className="rounded-xl border border-slate-800 bg-slate-950 p-5"><h2 className="mb-3 text-lg font-semibold">Payment</h2><p>Provider: {order.payment.provider||'—'}</p><p>Reference: {order.payment.reference||'—'}</p><p>Status: {order.paymentStatus}</p></section></div>
 <section className="overflow-x-auto rounded-xl border border-slate-800"><h2 className="p-5 text-lg font-semibold">Items</h2><table className="w-full min-w-[850px] text-sm"><thead><tr><th>Product</th><th>Variant</th><th>SKU</th><th>Quantity</th><th>Unit price</th><th>Line total</th></tr></thead><tbody>{order.items.map(item=><tr key={item.id} className="border-t border-slate-800"><td className="p-3">{item.productName}</td><td>{item.variantName}</td><td>{item.sku}</td><td>{item.quantity}</td><td>{money(item.unitPrice,order.currency)}</td><td>{money(item.lineTotal,order.currency)}</td></tr>)}</tbody></table></section>
 <section className="rounded-xl border border-slate-800 bg-slate-950 p-5"><h2 className="mb-3 text-lg font-semibold">Pricing</h2><div className="grid max-w-md gap-2 sm:grid-cols-2"><span>Subtotal</span><span>{money(order.subtotal,order.currency)}</span><span>Discount</span><span>{money(order.discountAmount,order.currency)}</span><span>Shipping</span><span>{money(order.shippingAmount,order.currency)}</span><span>Tax</span><span>{money(order.taxAmount,order.currency)}</span><strong>Total</strong><strong>{money(order.totalAmount,order.currency)}</strong><span>Currency</span><span>{order.currency}</span></div></section>
 <section className="overflow-x-auto rounded-xl border border-slate-800"><h2 className="p-5 text-lg font-semibold">Status history</h2>{order.statusHistory.length===0?<p className="p-5 text-slate-400">No status history.</p>:<table className="w-full min-w-[800px] text-sm"><thead><tr><th>Created</th><th>Previous status</th><th>New status</th><th>Changed by</th><th>Admin email</th><th>Note</th></tr></thead><tbody>{order.statusHistory.map(item=><tr key={item.id} className="border-t border-slate-800"><td className="p-3">{new Date(item.createdAt).toLocaleString()}</td><td>{item.previousStatus||'—'}</td><td>{item.newStatus}</td><td>{item.changedByName||'System'}</td><td>{item.changedByEmail||'—'}</td><td>{item.note||'—'}</td></tr>)}</tbody></table>}</section>
 {dialog&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><form aria-label="Update order status" className="w-full max-w-lg space-y-4 rounded-xl border border-slate-800 bg-slate-950 p-6" onSubmit={submit}><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Update status</h2><button type="button" aria-label="Close status dialog" disabled={saving} onClick={()=>setDialog(false)}><X aria-hidden="true"/></button></div><p>Current status: <strong>{order.orderStatus}</strong></p><label>New status<select aria-label="New order status" className="input-field mt-1 w-full" value={newStatus} onChange={e=>setNewStatus(e.target.value as OrderStatus)}>{allowedOrderStatuses.map(status=><option key={status} value={status}>{status}</option>)}</select></label><label>Note (optional)<textarea aria-label="Status note" maxLength={500} rows={3} className="input-field mt-1 w-full" value={note} onChange={e=>setNote(e.target.value)}/></label><div className="flex justify-end gap-2"><button type="button" className="btn-secondary" disabled={saving} onClick={()=>setDialog(false)}>Cancel</button><button type="submit" className="btn-primary" disabled={saving}>{saving?'Updating…':'Confirm'}</button></div></form></div>}
 {paymentDialog&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><form aria-label="Update payment status" className="w-full max-w-lg space-y-4 rounded-xl border border-slate-800 bg-slate-950 p-6" onSubmit={submitPayment}><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Update payment status</h2><button type="button" aria-label="Close payment dialog" disabled={saving} onClick={()=>setPaymentDialog(false)}><X aria-hidden="true"/></button></div><p>Order: <strong>{order.orderNumber}</strong></p><p>Customer: {order.customer.name}</p><p>Total: {money(order.totalAmount,order.currency)}</p><p>Current payment status: <strong>{order.paymentStatus}</strong></p>{newPaymentStatus==='REFUNDED'&&<p className="rounded-lg bg-amber-500/10 p-3 text-amber-300">Chỉ đánh dấu REFUNDED sau khi tiền đã được hoàn thủ công qua ngân hàng.</p>}<label>New payment status<select aria-label="New payment status" className="input-field mt-1 w-full" value={newPaymentStatus} onChange={e=>{setNewPaymentStatus(e.target.value as AdminPaymentStatusInput['status']);setPaymentNoteError('')}}>{paymentOptions[order.paymentStatus].map(status=><option key={status} value={status}>{status}</option>)}</select></label><label>Note {paymentNoteRequired?'(required)':'(optional)'}<textarea aria-label="Payment status note" aria-invalid={Boolean(paymentNoteError)} maxLength={500} rows={3} className="input-field mt-1 w-full" value={note} onChange={e=>{setNote(e.target.value);setPaymentNoteError('')}}/></label>{paymentNoteError&&<p role="alert" className="text-sm text-red-400">{paymentNoteError}</p>}<div className="flex justify-end gap-2"><button type="button" className="btn-secondary" disabled={saving} onClick={()=>setPaymentDialog(false)}>Cancel</button><button type="submit" className="btn-primary" disabled={saving}>{saving?'Updating…':'Confirm'}</button></div></form></div>}
 <section className="overflow-x-auto rounded-xl border border-slate-800"><h2 className="p-5 text-lg font-semibold">Payment history</h2>{order.paymentHistory.length===0?<p className="p-5 text-slate-400">No payment history.</p>:<table className="w-full min-w-[1100px] text-sm"><thead><tr><th>Created</th><th>Previous status</th><th>New status</th><th>Actor type</th><th>Changed by</th><th>Admin/User email</th><th>Payment reference</th><th>Note</th></tr></thead><tbody>{order.paymentHistory.map(item=><tr key={item.id} className="border-t border-slate-800"><td className="p-3">{new Date(item.createdAt).toLocaleString()}</td><td>{item.previousStatus}</td><td>{item.newStatus}</td><td>{item.actorType}</td><td>{item.changedByName||'—'}</td><td>{item.changedByEmail||'—'}</td><td>{item.paymentReference||'—'}</td><td>{item.note||'—'}</td></tr>)}</tbody></table>}</section>
 {configuration&&!configuration.bankTransfer.ready&&<p className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-amber-200">Cấu hình thanh toán ngân hàng chưa hoàn chỉnh.</p>}
 {configuration&&!configuration.mail.configured&&<p className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-amber-200">Gmail notification chưa được cấu hình đầy đủ. Payment status vẫn được lưu nhưng email sẽ không được gửi.</p>}
 </div>;
}
