import { getPool, sql } from '../../config/database';
import { AppError } from '../../middleware/errorHandler';

type Input = Record<string, unknown>;
type Variant = { id:number; product_id:number; is_active:boolean; is_default:boolean; sku:string; variant_name:string; price:number; sale_price:number|null; barcode:string|null; weight:number|null };
const select=`SELECT v.*,i.id inventory_id,i.on_hand,i.reserved,i.available,i.low_stock_threshold,CASE WHEN i.available<=0 THEN 'OUT_OF_STOCK' WHEN i.available<=i.low_stock_threshold THEN 'LOW_STOCK' ELSE 'IN_STOCK' END stock_status FROM dbo.ProductVariants v JOIN dbo.Inventory i ON i.variant_id=v.id`;
async function get(id:number){const p=await getPool();const r=await p.request().input('id',sql.Int,id).query(`${select} WHERE v.id=@id`);if(!r.recordset[0])throw new AppError(404,'Variant not found');return r.recordset[0] as Variant;}
async function lock(tx:sql.Transaction,id:number){const r=await tx.request().input('id',sql.Int,id).query('SELECT id,product_id,is_active,is_default FROM dbo.ProductVariants WITH (UPDLOCK,HOLDLOCK) WHERE id=@id');if(!r.recordset[0])throw new AppError(404,'Variant not found');return r.recordset[0] as Variant;}
async function verify(tx:sql.Transaction,productId:number){const r=await tx.request().input('productId',sql.Int,productId).query('SELECT p.is_active,(SELECT COUNT(*) FROM dbo.ProductVariants WHERE product_id=@productId AND is_active=1) active_count,(SELECT COUNT(*) FROM dbo.ProductVariants WHERE product_id=@productId AND is_active=1 AND is_default=1) default_count FROM dbo.Products p WHERE p.id=@productId');if(!r.recordset[0])throw new AppError(404,'Product not found');if(r.recordset[0].is_active&&(Number(r.recordset[0].active_count)<1||Number(r.recordset[0].default_count)!==1))throw new AppError(409,'An active Product must retain at least one active Variant.');}
export const adminVariantsService={
 async get(id:number){return get(id)},
 async list(productId:number){const p=await getPool();const r=await p.request().input('productId',sql.Int,productId).query(`${select} WHERE v.product_id=@productId ORDER BY v.is_default DESC,v.is_active DESC,v.id ASC`);return r.recordset;},
 async create(productId:number,input:Input){const p=await getPool();const tx=p.transaction();await tx.begin();try{const rows=(await tx.request().input('productId',sql.Int,productId).query('SELECT id,is_active,is_default FROM dbo.ProductVariants WITH (UPDLOCK,HOLDLOCK) WHERE product_id=@productId')).recordset;const product=await tx.request().input('product',sql.Int,productId).query('SELECT id FROM dbo.Products WHERE id=@product');if(!product.recordset[0])throw new AppError(404,'Product not found');const sku=String(input.sku).trim();const dup=await tx.request().input('sku',sql.NVarChar(200),sku).query('SELECT id FROM dbo.ProductVariants WHERE sku=@sku');if(dup.recordset[0])throw new AppError(409,'SKU already exists');const active=input.is_active!==false,makeDefault=active&&(input.is_default===true||!rows.some((x:{is_active:boolean})=>x.is_active));if(makeDefault)await tx.request().input('productId',sql.Int,productId).query('UPDATE dbo.ProductVariants SET is_default=0 WHERE product_id=@productId');const ins=await tx.request().input('productId',sql.Int,productId).input('name',sql.NVarChar(200),String(input.variant_name).trim()).input('sku',sql.NVarChar(200),sku).input('price',sql.Decimal(10,2),Number(input.price)).input('sale',sql.Decimal(10,2),input.sale_price??null).input('barcode',sql.NVarChar(100),input.barcode??null).input('weight',sql.Decimal(8,3),input.weight??null).input('active',sql.Bit,active).input('def',sql.Bit,makeDefault).query('INSERT dbo.ProductVariants(product_id,variant_name,sku,price,sale_price,barcode,weight,is_active,is_default,created_at,updated_at) OUTPUT INSERTED.id VALUES(@productId,@name,@sku,@price,@sale,@barcode,@weight,@active,@def,SYSUTCDATETIME(),SYSUTCDATETIME())');const id=ins.recordset[0].id;await tx.request().input('id',sql.Int,id).input('stock',sql.Int,Number(input.initial_on_hand||0)).input('threshold',sql.Int,Number(input.low_stock_threshold||10)).query('INSERT dbo.Inventory(variant_id,on_hand,reserved,low_stock_threshold,updated_at) VALUES(@id,@stock,0,@threshold,SYSUTCDATETIME())');await verify(tx,productId);await tx.commit();return get(id)}catch(e:unknown){await tx.rollback();throw e;}},
 async setDefault(id:number){const p=await getPool();const tx=p.transaction();await tx.begin();try{const v=await lock(tx,id);if(!v.is_active)throw new AppError(409,'Inactive Variant cannot be default');await tx.request().input('productId',sql.Int,v.product_id).query('UPDATE dbo.ProductVariants SET is_default=0 WHERE product_id=@productId');await tx.request().input('id',sql.Int,id).query('UPDATE dbo.ProductVariants SET is_default=1 WHERE id=@id');await verify(tx,v.product_id);await tx.commit();return get(id)}catch(e:unknown){await tx.rollback();throw e;}},
 async update(id:number,input:Input){if(['stock','on_hand','reserved','available'].some(k=>k in input))throw new AppError(400,'Stock must be changed through inventory adjustment API');const v=await get(id);const p=await getPool();await p.request().input('id',sql.Int,id).input('price',sql.Decimal(10,2),Number(input.price??v.price)).input('name',sql.NVarChar(200),String(input.variant_name??v.variant_name)).query('UPDATE dbo.ProductVariants SET price=@price,variant_name=@name,updated_at=SYSUTCDATETIME() WHERE id=@id');return get(id)},
 async remove(id:number){const p=await getPool();const tx=p.transaction();let started=false;try{await tx.begin();started=true;const target=await lock(tx,id);const set=(await tx.request().input('productId',sql.Int,target.product_id).query('SELECT id,is_active,is_default FROM dbo.ProductVariants WITH (UPDLOCK,HOLDLOCK) WHERE product_id=@productId ORDER BY id')).recordset as Variant[];const active=set.filter(v=>v.is_active);const product=(await tx.request().input('productId2',sql.Int,target.product_id).query('SELECT is_active FROM dbo.Products WHERE id=@productId2')).recordset[0];if(product.is_active&&target.is_active&&active.length===1)throw new AppError(409,'An active Product must retain at least one active Variant.');const replacement=target.is_active&&target.is_default?active.find(v=>v.id!==id):undefined;const history=await tx.request().input('id',sql.Int,id).query('SELECT COUNT(*) total FROM dbo.InventoryAdjustments WHERE variant_id=@id OR inventory_id IN(SELECT id FROM dbo.Inventory WHERE variant_id=@id)');if(target.is_default&&replacement){await tx.request().input('id',sql.Int,id).query('UPDATE dbo.ProductVariants SET is_default=0,updated_at=SYSUTCDATETIME() WHERE id=@id AND is_default=1');await tx.request().input('replacement',sql.Int,replacement.id).query('UPDATE dbo.ProductVariants SET is_default=1,updated_at=SYSUTCDATETIME() WHERE id=@replacement AND is_active=1');}let action='DELETED';if(Number(history.recordset[0].total)>0){action='DISABLED_REFERENCED';await tx.request().input('id',sql.Int,id).query('UPDATE dbo.ProductVariants SET is_active=0,is_default=0,updated_at=SYSUTCDATETIME() WHERE id=@id');}else{await tx.request().input('id',sql.Int,id).query('DELETE FROM dbo.VariantOptionValues WHERE variant_id=@id; DELETE FROM dbo.Inventory WHERE variant_id=@id; DELETE FROM dbo.ProductVariants WHERE id=@id');}await verify(tx,target.product_id);await tx.commit();started=false;return {action,variantId:id,newDefaultVariantId:replacement?.id??null};}catch(e:unknown){if(started)await tx.rollback();throw e;}}
};
